# all available settings of specific linters
linters-settings:
  errcheck:
    ignore: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema:Set

linters:
  enable:
    - deadcode
    - errcheck
    - gofmt
    - goimports
    - gosimple
    - ineffassign
    - misspell
    - staticcheck
    - structcheck
    - unconvert
    - unused
    - varcheck
    - vet
  disable-all: true
