name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.14.x
      - uses: golangci/golangci-lint-action@v2
        with:
          version: v1.29
