name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.14.x
      - run: go install github.com/golangci/golangci-lint/cmd/golangci-lint
      - run: golangci-lint run ./mackerel/...
