name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.15.x
      - uses: golangci/golangci-lint-action@v2
        with:
          version: v1.29

  acceptance-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.14.x
      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - run: go test ./... -v -timeout=120m -coverprofile=coverage.txt -covermode=atomic
        env:
          TF_ACC: 1
          MACKEREL_API_KEY: ${{ secrets.MACKEREL_API_KEY }}
      - uses: codecov/codecov-action@v1
