name: test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup go 1.12.x
        uses: actions/setup-go@v1
        with:
          go-version: 1.12.x
      - name: Run test
        run: go test -cover -timeout=30s -parallel=4 ./...
